CREATE USER nombreusuario IDENTIFIED BY "contraseñausuario"
DEFAULT TABLESPACE DATA TEMPORARY TABLESPACE TEMP;
GRANT CREATE SESSION TO nombreusuario;
GRANT CREATE TABLE TO nombreusuario;
GRANT CREATE SEQUENCE TO nombreusuario;
ALTER USER nombreusuario QUOTA UNLIMITED ON DATA;
