CREATE USER lmsepulvedac IDENTIFIED BY "Elgatoconbot4s"
DEFAULT TABLESPACE DATA TEMPORARY TABLESPACE TEMP;
GRANT CREATE SESSION TO lmsepulvedac;
GRANT CREATE TABLE TO lmsepulvedac;
GRANT CREATE SEQUENCE TO lmsepulvedac;
ALTER USER lmsepulvedac QUOTA UNLIMITED ON DATA;
